quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS:*}
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type,Accept,Authorization

quarkus.lambda.handler=io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest

quarkus.log.level=INFO
quarkus.log.category."com.symplex".level=DEBUG
